env:
  browser: true
  es2022: true
ignorePatterns:
  - js/
overrides:
  - files: ["*.mts"]
    parserOptions:
      sourceType: module
plugins: ['@typescript-eslint']
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  comma-dangle:
    - error
    - always-multiline
  linebreak-style:
    - error
    - unix
  prefer-const:
    - error
    - destructuring: all
  quotes:
    - error
    - single
  quote-props:
    - error
  semi:
    - error
    - always
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
  '@typescript-eslint/no-explicit-any':
    - off
